// src/pages/UploadPage.js
// UC-01: Upload Dataset  |  UC-02: Preview Dataset
// Enhanced to display BLL data quality report from ingest_bll.py
//   - BR-ING-01: File extension validation
//   - BR-ING-02: File size limit
//   - BR-ING-07: Data quality score, missing data analysis, column type breakdown
//   - DT-ING-01/02: CSV → DataFrame → JSON preview

import React, { useState, useCallback } from 'react';
import { useDropzone } from 'react-dropzone';
import { useNavigate } from 'react-router-dom';
import axios from 'axios';
import { useApp } from '../context/AppContext';
import DataGrid from '../components/DataGrid';

export default function UploadPage() {
  const [status,  setStatus]  = useState('idle');
  const [message, setMessage] = useState('');
  const [qualityReport, setQualityReport] = useState(null);
  const { dataset, setDataset } = useApp();
  const navigate = useNavigate();

  const onDrop = useCallback(async (acceptedFiles, rejectedFiles) => {
    // Client-side validation (mirrors BR-ING-01)
    if (rejectedFiles.length > 0) {
      setStatus('error');
      setMessage('Only .csv files are accepted (BR-ING-01).');
      return;
    }

    const file = acceptedFiles[0];
    if (!file.name.toLowerCase().endsWith('.csv')) {
      setStatus('error');
      setMessage('Invalid file type. Only .csv files are accepted (BR-ING-01).');
      return;
    }

    // Client-side size check (mirrors BR-ING-02)
    const sizeMB = file.size / (1024 * 1024);
    if (sizeMB > 50) {
      setStatus('error');
      setMessage(`File size (${sizeMB.toFixed(1)} MB) exceeds the 50 MB limit (BR-ING-02).`);
      return;
    }

    setStatus('uploading');
    setMessage('');
    setQualityReport(null);

    try {
      const form = new FormData();
      form.append('file', file);

      const res = await axios.post('/api/ingest/upload', form, {
        headers: { 'Content-Type': 'multipart/form-data' },
      });

      // res.data now includes quality_report from BLL (BR-ING-07)
      setDataset({
        datasetId: res.data.dataset_id,
        filename:  res.data.filename,
        columns:   res.data.columns,
        preview:   res.data.preview,
        rowCount:  res.data.row_count,
      });
      setQualityReport(res.data.quality_report || null);
      setStatus('done');
      setMessage(`Successfully uploaded "${res.data.filename}" with ${res.data.row_count} rows.`);
    } catch (err) {
      setStatus('error');
      const detail = err.response?.data?.detail;
      if (Array.isArray(detail)) {
        setMessage(detail.join(' '));
      } else {
        setMessage(detail || 'Upload failed. Please try again.');
      }
    }
  }, [setDataset]);

  const { getRootProps, getInputProps, isDragActive } = useDropzone({
    onDrop,
    accept: { 'text/csv': ['.csv'] },
    maxFiles: 1,
    multiple: false,
  });

  // Quality score color
  const scoreColor = (score) => {
    if (score >= 80) return '#22C55E';
    if (score >= 60) return '#F59E0B';
    return '#EF4444';
  };

  return (
    <div>
      <div className="page-header">
        <h1>📂 Upload Dataset</h1>
        <p>Upload a real estate CSV dataset to begin the AutoML pipeline</p>
      </div>

      {/* Step 1: Drop zone */}
      <div className="card">
        <div className="card-title">Step 1 — Select Your Dataset</div>
        <div className="card-subtitle">
          Supported format: CSV with property features (bedrooms, area, location, price, etc.)
        </div>

        <div
          {...getRootProps()}
          className={`dropzone ${isDragActive ? 'active' : ''}`}
        >
          <input {...getInputProps()} />
          <div className="dropzone-icon">
            {status === 'uploading' ? '⏳' : isDragActive ? '📥' : '📄'}
          </div>
          {status === 'uploading' ? (
            <p>Uploading and validating via BLL… please wait.</p>
          ) : isDragActive ? (
            <p><strong>Drop it here!</strong></p>
          ) : (
            <p>
              <strong>Drag & drop a CSV file here</strong>
              <br />or click to browse
            </p>
          )}
        </div>

        {status === 'done' && (
          <div className="alert alert-success mt-4">✓ {message}</div>
        )}
        {status === 'error' && (
          <div className="alert alert-error mt-4">⚠ {message}</div>
        )}
      </div>

      {/* BLL Data Quality Report (BR-ING-07) */}
      {qualityReport && (
        <div className="card">
          <div className="card-title">📊 Data Quality Report (BLL: ingest_bll.py)</div>
          <div className="card-subtitle">
            Generated by the Business Logic Layer during ingestion (BR-ING-07)
          </div>

          {/* Quality Score */}
          <div style={{
            display: 'flex', alignItems: 'center', gap: 16, marginBottom: 20,
            padding: '16px 20px', background: 'var(--color-bg)',
            borderRadius: 12, border: '1px solid var(--color-border)',
          }}>
            <div style={{
              width: 64, height: 64, borderRadius: '50%',
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              fontSize: 22, fontWeight: 800, color: '#fff',
              background: scoreColor(qualityReport.quality_score),
            }}>
              {qualityReport.quality_score}
            </div>
            <div>
              <div style={{ fontWeight: 700, fontSize: 16 }}>Quality Score</div>
              <div style={{ color: 'var(--color-muted)', fontSize: 13 }}>
                Based on missing data, duplicates, and dataset size
              </div>
            </div>
          </div>

          {/* Summary metrics */}
          <div className="metric-grid">
            <div className="metric-card">
              <div className="metric-label">Total Rows</div>
              <div className="metric-value">{qualityReport.total_rows?.toLocaleString()}</div>
            </div>
            <div className="metric-card">
              <div className="metric-label">Total Columns</div>
              <div className="metric-value">{qualityReport.total_columns}</div>
            </div>
            <div className="metric-card">
              <div className="metric-label">Missing Cells</div>
              <div className="metric-value">{qualityReport.missing_cells} ({qualityReport.missing_pct}%)</div>
            </div>
            <div className="metric-card">
              <div className="metric-label">Duplicate Rows</div>
              <div className="metric-value">{qualityReport.duplicate_rows}</div>
            </div>
          </div>

          {/* Column Type Breakdown (DT-ING-03) */}
          <div style={{ display: 'flex', gap: 12, marginTop: 16, flexWrap: 'wrap' }}>
            <div style={{ flex: 1, minWidth: 200 }}>
              <div style={{ fontWeight: 600, fontSize: 13, marginBottom: 8 }}>
                Numeric Columns ({qualityReport.numeric_columns?.length || 0})
              </div>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4 }}>
                {(qualityReport.numeric_columns || []).map(col => (
                  <span key={col} className="tag tag-green">{col}</span>
                ))}
              </div>
            </div>
            <div style={{ flex: 1, minWidth: 200 }}>
              <div style={{ fontWeight: 600, fontSize: 13, marginBottom: 8 }}>
                Categorical Columns ({qualityReport.categorical_columns?.length || 0})
              </div>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4 }}>
                {(qualityReport.categorical_columns || []).map(col => (
                  <span key={col} className="tag tag-orange">{col}</span>
                ))}
              </div>
            </div>
          </div>

          {/* Per-column quality (BR-ING-07) */}
          {qualityReport.column_quality && (
            <div style={{ marginTop: 16 }}>
              <div style={{ fontWeight: 600, fontSize: 13, marginBottom: 8 }}>Per-Column Details</div>
              <div className="data-grid-wrap">
                <table className="data-grid">
                  <thead>
                    <tr>
                      <th>Column</th>
                      <th>Type</th>
                      <th>Missing</th>
                      <th>Missing %</th>
                      <th>Unique</th>
                    </tr>
                  </thead>
                  <tbody>
                    {Object.entries(qualityReport.column_quality).map(([col, info]) => (
                      <tr key={col}>
                        <td><strong>{col}</strong></td>
                        <td><span className="tag tag-blue">{info.dtype}</span></td>
                        <td>{info.missing}</td>
                        <td style={{ color: info.missing_pct > 10 ? '#EF4444' : 'inherit' }}>
                          {info.missing_pct}%
                        </td>
                        <td>{info.unique}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}
        </div>
      )}

      {/* Step 2: Preview */}
      {dataset && (
        <div className="card">
          <div className="flex-between mb-4">
            <div>
              <div className="card-title">Step 2 — Dataset Preview (DT-ING-02)</div>
              <div className="card-subtitle" style={{ marginBottom: 0 }}>
                {dataset.filename} &nbsp;·&nbsp;
                <span className="tag tag-blue">{dataset.rowCount.toLocaleString()} rows</span>
                &nbsp;&nbsp;
                <span className="tag tag-orange">{dataset.columns.length} columns</span>
              </div>
            </div>
            <button className="btn btn-primary" onClick={() => navigate('/train')}>
              Proceed to Training →
            </button>
          </div>

          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6, marginBottom: 20 }}>
            {dataset.columns.map(col => (
              <span key={col} className="tag tag-blue">{col}</span>
            ))}
          </div>

          <DataGrid columns={dataset.columns} rows={dataset.preview} />
        </div>
      )}

      {/* Instructions */}
      {!dataset && status === 'idle' && (
        <div className="card mt-4">
          <div className="card-title">Expected Dataset Format</div>
          <div className="card-subtitle">Your CSV should contain columns such as:</div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6 }}>
            {['bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors',
              'waterfront', 'view', 'condition', 'grade', 'yr_built',
              'zipcode', 'lat', 'long', 'price'].map(c => (
              <span key={c} className="tag tag-blue">{c}</span>
            ))}
          </div>
          <p className="text-muted mt-4" style={{ fontSize: 13 }}>
            The <strong>price</strong> (or equivalent) column will be used as the prediction target.
          </p>

          {/* BLL info */}
          <div style={{ background: 'rgba(46,117,182,0.05)', borderRadius: 8, padding: '10px 14px', marginTop: 12 }}>
            <div style={{ fontSize: 11, color: '#6B7280', fontWeight: 600, marginBottom: 4 }}>
              🔧 BLL Validations Applied on Upload
            </div>
            <div style={{ fontSize: 11, color: '#9CA3AF' }}>
              BR-ING-01: File extension check &nbsp;·&nbsp;
              BR-ING-02: 50 MB size limit &nbsp;·&nbsp;
              BR-ING-04: Non-empty check &nbsp;·&nbsp;
              BR-ING-05: Min 2 columns &nbsp;·&nbsp;
              BR-ING-06: Min 10 rows &nbsp;·&nbsp;
              BR-ING-07: Quality scoring
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
